// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	team "github.com/delyke/tasks_and_commands_service/internal/domain/team"
	mock "github.com/stretchr/testify/mock"

	user "github.com/delyke/tasks_and_commands_service/internal/domain/user"
)

// MemberRepository is an autogenerated mock type for the MemberRepository type
type MemberRepository struct {
	mock.Mock
}

type MemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberRepository) EXPECT() *MemberRepository_Expecter {
	return &MemberRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, member
func (_m *MemberRepository) Add(ctx context.Context, member *team.Member) (team.MemberID, error) {
	ret := _m.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 team.MemberID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *team.Member) (team.MemberID, error)); ok {
		return rf(ctx, member)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *team.Member) team.MemberID); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Get(0).(team.MemberID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *team.Member) error); ok {
		r1 = rf(ctx, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MemberRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - member *team.Member
func (_e *MemberRepository_Expecter) Add(ctx interface{}, member interface{}) *MemberRepository_Add_Call {
	return &MemberRepository_Add_Call{Call: _e.mock.On("Add", ctx, member)}
}

func (_c *MemberRepository_Add_Call) Run(run func(ctx context.Context, member *team.Member)) *MemberRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*team.Member))
	})
	return _c
}

func (_c *MemberRepository_Add_Call) Return(_a0 team.MemberID, _a1 error) *MemberRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_Add_Call) RunAndReturn(run func(context.Context, *team.Member) (team.MemberID, error)) *MemberRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeamAndUser provides a mock function with given fields: ctx, teamID, userID
func (_m *MemberRepository) GetByTeamAndUser(ctx context.Context, teamID team.ID, userID user.ID) (*team.Member, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamAndUser")
	}

	var r0 *team.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, user.ID) (*team.Member, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, user.ID) *team.Member); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, team.ID, user.ID) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_GetByTeamAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeamAndUser'
type MemberRepository_GetByTeamAndUser_Call struct {
	*mock.Call
}

// GetByTeamAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID team.ID
//   - userID user.ID
func (_e *MemberRepository_Expecter) GetByTeamAndUser(ctx interface{}, teamID interface{}, userID interface{}) *MemberRepository_GetByTeamAndUser_Call {
	return &MemberRepository_GetByTeamAndUser_Call{Call: _e.mock.On("GetByTeamAndUser", ctx, teamID, userID)}
}

func (_c *MemberRepository_GetByTeamAndUser_Call) Run(run func(ctx context.Context, teamID team.ID, userID user.ID)) *MemberRepository_GetByTeamAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(team.ID), args[2].(user.ID))
	})
	return _c
}

func (_c *MemberRepository_GetByTeamAndUser_Call) Return(_a0 *team.Member, _a1 error) *MemberRepository_GetByTeamAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_GetByTeamAndUser_Call) RunAndReturn(run func(context.Context, team.ID, user.ID) (*team.Member, error)) *MemberRepository_GetByTeamAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function with given fields: ctx, teamID, userID
func (_m *MemberRepository) IsMember(ctx context.Context, teamID team.ID, userID user.ID) (bool, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, user.ID) (bool, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, user.ID) bool); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, team.ID, user.ID) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type MemberRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID team.ID
//   - userID user.ID
func (_e *MemberRepository_Expecter) IsMember(ctx interface{}, teamID interface{}, userID interface{}) *MemberRepository_IsMember_Call {
	return &MemberRepository_IsMember_Call{Call: _e.mock.On("IsMember", ctx, teamID, userID)}
}

func (_c *MemberRepository_IsMember_Call) Run(run func(ctx context.Context, teamID team.ID, userID user.ID)) *MemberRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(team.ID), args[2].(user.ID))
	})
	return _c
}

func (_c *MemberRepository_IsMember_Call) Return(_a0 bool, _a1 error) *MemberRepository_IsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_IsMember_Call) RunAndReturn(run func(context.Context, team.ID, user.ID) (bool, error)) *MemberRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTeam provides a mock function with given fields: ctx, teamID
func (_m *MemberRepository) ListByTeam(ctx context.Context, teamID team.ID) ([]*team.Member, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeam")
	}

	var r0 []*team.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, team.ID) ([]*team.Member, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, team.ID) []*team.Member); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, team.ID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_ListByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTeam'
type MemberRepository_ListByTeam_Call struct {
	*mock.Call
}

// ListByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID team.ID
func (_e *MemberRepository_Expecter) ListByTeam(ctx interface{}, teamID interface{}) *MemberRepository_ListByTeam_Call {
	return &MemberRepository_ListByTeam_Call{Call: _e.mock.On("ListByTeam", ctx, teamID)}
}

func (_c *MemberRepository_ListByTeam_Call) Run(run func(ctx context.Context, teamID team.ID)) *MemberRepository_ListByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(team.ID))
	})
	return _c
}

func (_c *MemberRepository_ListByTeam_Call) Return(_a0 []*team.Member, _a1 error) *MemberRepository_ListByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_ListByTeam_Call) RunAndReturn(run func(context.Context, team.ID) ([]*team.Member, error)) *MemberRepository_ListByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MemberRepository) ListByUser(ctx context.Context, userID user.ID) ([]*team.Member, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*team.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) ([]*team.Member, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) []*team.Member); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*team.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.ID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MemberRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID user.ID
func (_e *MemberRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MemberRepository_ListByUser_Call {
	return &MemberRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MemberRepository_ListByUser_Call) Run(run func(ctx context.Context, userID user.ID)) *MemberRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ID))
	})
	return _c
}

func (_c *MemberRepository_ListByUser_Call) Return(_a0 []*team.Member, _a1 error) *MemberRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberRepository_ListByUser_Call) RunAndReturn(run func(context.Context, user.ID) ([]*team.Member, error)) *MemberRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, teamID, userID
func (_m *MemberRepository) Remove(ctx context.Context, teamID team.ID, userID user.ID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, user.ID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MemberRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID team.ID
//   - userID user.ID
func (_e *MemberRepository_Expecter) Remove(ctx interface{}, teamID interface{}, userID interface{}) *MemberRepository_Remove_Call {
	return &MemberRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, teamID, userID)}
}

func (_c *MemberRepository_Remove_Call) Run(run func(ctx context.Context, teamID team.ID, userID user.ID)) *MemberRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(team.ID), args[2].(user.ID))
	})
	return _c
}

func (_c *MemberRepository_Remove_Call) Return(_a0 error) *MemberRepository_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_Remove_Call) RunAndReturn(run func(context.Context, team.ID, user.ID) error) *MemberRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, id, role
func (_m *MemberRepository) UpdateRole(ctx context.Context, id team.MemberID, role team.Role) error {
	ret := _m.Called(ctx, id, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, team.MemberID, team.Role) error); ok {
		r0 = rf(ctx, id, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MemberRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MemberRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id team.MemberID
//   - role team.Role
func (_e *MemberRepository_Expecter) UpdateRole(ctx interface{}, id interface{}, role interface{}) *MemberRepository_UpdateRole_Call {
	return &MemberRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, role)}
}

func (_c *MemberRepository_UpdateRole_Call) Run(run func(ctx context.Context, id team.MemberID, role team.Role)) *MemberRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(team.MemberID), args[2].(team.Role))
	})
	return _c
}

func (_c *MemberRepository_UpdateRole_Call) Return(_a0 error) *MemberRepository_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MemberRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, team.MemberID, team.Role) error) *MemberRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberRepository creates a new instance of MemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberRepository {
	mock := &MemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
