// Code generated by ogen, DO NOT EDIT.

package tasks_v1

// setDefaults set default value of fields.
func (s *CreateTaskReq) setDefaults() {
	{
		val := CreateTaskReqStatus("todo")
		s.Status.SetTo(val)
	}
	{
		val := CreateTaskReqPriority("medium")
		s.Priority.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *InviteUserToTeamReq) setDefaults() {
	{
		val := InviteUserToTeamReqRole("member")
		s.Role.SetTo(val)
	}
}
