// Code generated by ogen, DO NOT EDIT.

package tasks_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements CreateTask operation.
//
// Создать новую задачу (только для членов команды).
//
// POST /api/v1/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskReq) (r CreateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTeam implements CreateTeam operation.
//
// Создать новую команду (текущий пользователь
// становится owner).
//
// POST /api/v1/teams
func (UnimplementedHandler) CreateTeam(ctx context.Context, req *CreateTeamReq) (r CreateTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskHistory implements GetTaskHistory operation.
//
// История изменений задачи.
//
// GET /api/v1/tasks/{id}/history
func (UnimplementedHandler) GetTaskHistory(ctx context.Context, params GetTaskHistoryParams) (r GetTaskHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InviteUserToTeam implements InviteUserToTeam operation.
//
// Пригласить пользователя в команду (только owner/admin).
//
// POST /api/v1/teams/{id}/invite
func (UnimplementedHandler) InviteUserToTeam(ctx context.Context, req *InviteUserToTeamReq, params InviteUserToTeamParams) (r InviteUserToTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements ListTasks operation.
//
// Список задач с фильтрацией и пагинацией.
//
// GET /api/v1/tasks
func (UnimplementedHandler) ListTasks(ctx context.Context, params ListTasksParams) (r ListTasksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTeams implements ListTeams operation.
//
// Список команд, в которых состоит текущий пользователь.
//
// GET /api/v1/teams
func (UnimplementedHandler) ListTeams(ctx context.Context, params ListTeamsParams) (r ListTeamsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginUser implements LoginUser operation.
//
// Аутентификация пользователя и получение JWT-токена.
//
// POST /api/v1/login
func (UnimplementedHandler) LoginUser(ctx context.Context, req *LoginUserReq) (r LoginUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements RegisterUser operation.
//
// Регистрация нового пользователя в системе.
//
// POST /api/v1/register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterUserReq) (r RegisterUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements UpdateTask operation.
//
// Обновить задачу (проверка прав доступа).
//
// PUT /api/v1/tasks/{id}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *UpdateTaskReq, params UpdateTaskParams) (r UpdateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
