// Code generated by ogen, DO NOT EDIT.

package tasks_v1

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ошибка валидации входных данных.
// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	Code    int32                        `json:"code"`
	Message string                       `json:"message"`
	Details []BadRequestErrorDetailsItem `json:"details"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *BadRequestError) GetDetails() []BadRequestErrorDetailsItem {
	return s.Details
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *BadRequestError) SetDetails(val []BadRequestErrorDetailsItem) {
	s.Details = val
}

func (*BadRequestError) createTaskRes()       {}
func (*BadRequestError) createTeamRes()       {}
func (*BadRequestError) inviteUserToTeamRes() {}
func (*BadRequestError) listTasksRes()        {}
func (*BadRequestError) loginUserRes()        {}
func (*BadRequestError) registerUserRes()     {}
func (*BadRequestError) updateTaskRes()       {}

type BadRequestErrorDetailsItem struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// GetField returns the value of Field.
func (s *BadRequestErrorDetailsItem) GetField() string {
	return s.Field
}

// GetMessage returns the value of Message.
func (s *BadRequestErrorDetailsItem) GetMessage() string {
	return s.Message
}

// SetField sets the value of Field.
func (s *BadRequestErrorDetailsItem) SetField(val string) {
	s.Field = val
}

// SetMessage sets the value of Message.
func (s *BadRequestErrorDetailsItem) SetMessage(val string) {
	s.Message = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Конфликт — ресурс уже существует.
// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) inviteUserToTeamRes() {}
func (*ConflictError) registerUserRes()     {}

type CreateTaskReq struct {
	Title       string                   `json:"title"`
	Description OptString                `json:"description"`
	Status      OptCreateTaskReqStatus   `json:"status"`
	Priority    OptCreateTaskReqPriority `json:"priority"`
	TeamID      int64                    `json:"team_id"`
	AssigneeID  OptInt64                 `json:"assignee_id"`
	DueDate     OptDateTime              `json:"due_date"`
}

// GetTitle returns the value of Title.
func (s *CreateTaskReq) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *CreateTaskReq) GetDescription() OptString {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *CreateTaskReq) GetStatus() OptCreateTaskReqStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *CreateTaskReq) GetPriority() OptCreateTaskReqPriority {
	return s.Priority
}

// GetTeamID returns the value of TeamID.
func (s *CreateTaskReq) GetTeamID() int64 {
	return s.TeamID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *CreateTaskReq) GetAssigneeID() OptInt64 {
	return s.AssigneeID
}

// GetDueDate returns the value of DueDate.
func (s *CreateTaskReq) GetDueDate() OptDateTime {
	return s.DueDate
}

// SetTitle sets the value of Title.
func (s *CreateTaskReq) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *CreateTaskReq) SetDescription(val OptString) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *CreateTaskReq) SetStatus(val OptCreateTaskReqStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *CreateTaskReq) SetPriority(val OptCreateTaskReqPriority) {
	s.Priority = val
}

// SetTeamID sets the value of TeamID.
func (s *CreateTaskReq) SetTeamID(val int64) {
	s.TeamID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *CreateTaskReq) SetAssigneeID(val OptInt64) {
	s.AssigneeID = val
}

// SetDueDate sets the value of DueDate.
func (s *CreateTaskReq) SetDueDate(val OptDateTime) {
	s.DueDate = val
}

type CreateTaskReqPriority string

const (
	CreateTaskReqPriorityLow    CreateTaskReqPriority = "low"
	CreateTaskReqPriorityMedium CreateTaskReqPriority = "medium"
	CreateTaskReqPriorityHigh   CreateTaskReqPriority = "high"
)

// AllValues returns all CreateTaskReqPriority values.
func (CreateTaskReqPriority) AllValues() []CreateTaskReqPriority {
	return []CreateTaskReqPriority{
		CreateTaskReqPriorityLow,
		CreateTaskReqPriorityMedium,
		CreateTaskReqPriorityHigh,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateTaskReqPriority) MarshalText() ([]byte, error) {
	switch s {
	case CreateTaskReqPriorityLow:
		return []byte(s), nil
	case CreateTaskReqPriorityMedium:
		return []byte(s), nil
	case CreateTaskReqPriorityHigh:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateTaskReqPriority) UnmarshalText(data []byte) error {
	switch CreateTaskReqPriority(data) {
	case CreateTaskReqPriorityLow:
		*s = CreateTaskReqPriorityLow
		return nil
	case CreateTaskReqPriorityMedium:
		*s = CreateTaskReqPriorityMedium
		return nil
	case CreateTaskReqPriorityHigh:
		*s = CreateTaskReqPriorityHigh
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateTaskReqStatus string

const (
	CreateTaskReqStatusTodo       CreateTaskReqStatus = "todo"
	CreateTaskReqStatusInProgress CreateTaskReqStatus = "in_progress"
	CreateTaskReqStatusDone       CreateTaskReqStatus = "done"
)

// AllValues returns all CreateTaskReqStatus values.
func (CreateTaskReqStatus) AllValues() []CreateTaskReqStatus {
	return []CreateTaskReqStatus{
		CreateTaskReqStatusTodo,
		CreateTaskReqStatusInProgress,
		CreateTaskReqStatusDone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateTaskReqStatus) MarshalText() ([]byte, error) {
	switch s {
	case CreateTaskReqStatusTodo:
		return []byte(s), nil
	case CreateTaskReqStatusInProgress:
		return []byte(s), nil
	case CreateTaskReqStatusDone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateTaskReqStatus) UnmarshalText(data []byte) error {
	switch CreateTaskReqStatus(data) {
	case CreateTaskReqStatusTodo:
		*s = CreateTaskReqStatusTodo
		return nil
	case CreateTaskReqStatusInProgress:
		*s = CreateTaskReqStatusInProgress
		return nil
	case CreateTaskReqStatusDone:
		*s = CreateTaskReqStatusDone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateTeamReq struct {
	Name        string    `json:"name"`
	Description OptString `json:"description"`
}

// GetName returns the value of Name.
func (s *CreateTeamReq) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateTeamReq) GetDescription() OptString {
	return s.Description
}

// SetName sets the value of Name.
func (s *CreateTeamReq) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateTeamReq) SetDescription(val OptString) {
	s.Description = val
}

// Доступ запрещён.
// Ref: #/components/schemas/forbidden_error
type ForbiddenError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ForbiddenError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ForbiddenError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val string) {
	s.Message = val
}

func (*ForbiddenError) createTaskRes()       {}
func (*ForbiddenError) getTaskHistoryRes()   {}
func (*ForbiddenError) inviteUserToTeamRes() {}
func (*ForbiddenError) updateTaskRes()       {}

// Непредвиденная ошибка.
// Ref: #/components/schemas/generic_error
type GenericError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

type GetTaskHistoryOK struct {
	History    []TaskHistoryEntry `json:"history"`
	Pagination Pagination         `json:"pagination"`
}

// GetHistory returns the value of History.
func (s *GetTaskHistoryOK) GetHistory() []TaskHistoryEntry {
	return s.History
}

// GetPagination returns the value of Pagination.
func (s *GetTaskHistoryOK) GetPagination() Pagination {
	return s.Pagination
}

// SetHistory sets the value of History.
func (s *GetTaskHistoryOK) SetHistory(val []TaskHistoryEntry) {
	s.History = val
}

// SetPagination sets the value of Pagination.
func (s *GetTaskHistoryOK) SetPagination(val Pagination) {
	s.Pagination = val
}

func (*GetTaskHistoryOK) getTaskHistoryRes() {}

// Внутренняя ошибка сервера.
// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) createTaskRes()       {}
func (*InternalServerError) createTeamRes()       {}
func (*InternalServerError) getTaskHistoryRes()   {}
func (*InternalServerError) inviteUserToTeamRes() {}
func (*InternalServerError) listTasksRes()        {}
func (*InternalServerError) listTeamsRes()        {}
func (*InternalServerError) loginUserRes()        {}
func (*InternalServerError) registerUserRes()     {}
func (*InternalServerError) updateTaskRes()       {}

type InviteUserToTeamReq struct {
	// Идентификатор приглашаемого пользователя.
	UserID int64 `json:"user_id"`
	// Роль пользователя в команде.
	Role OptInviteUserToTeamReqRole `json:"role"`
}

// GetUserID returns the value of UserID.
func (s *InviteUserToTeamReq) GetUserID() int64 {
	return s.UserID
}

// GetRole returns the value of Role.
func (s *InviteUserToTeamReq) GetRole() OptInviteUserToTeamReqRole {
	return s.Role
}

// SetUserID sets the value of UserID.
func (s *InviteUserToTeamReq) SetUserID(val int64) {
	s.UserID = val
}

// SetRole sets the value of Role.
func (s *InviteUserToTeamReq) SetRole(val OptInviteUserToTeamReqRole) {
	s.Role = val
}

// Роль пользователя в команде.
type InviteUserToTeamReqRole string

const (
	InviteUserToTeamReqRoleAdmin  InviteUserToTeamReqRole = "admin"
	InviteUserToTeamReqRoleMember InviteUserToTeamReqRole = "member"
)

// AllValues returns all InviteUserToTeamReqRole values.
func (InviteUserToTeamReqRole) AllValues() []InviteUserToTeamReqRole {
	return []InviteUserToTeamReqRole{
		InviteUserToTeamReqRoleAdmin,
		InviteUserToTeamReqRoleMember,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s InviteUserToTeamReqRole) MarshalText() ([]byte, error) {
	switch s {
	case InviteUserToTeamReqRoleAdmin:
		return []byte(s), nil
	case InviteUserToTeamReqRoleMember:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *InviteUserToTeamReqRole) UnmarshalText(data []byte) error {
	switch InviteUserToTeamReqRole(data) {
	case InviteUserToTeamReqRoleAdmin:
		*s = InviteUserToTeamReqRoleAdmin
		return nil
	case InviteUserToTeamReqRoleMember:
		*s = InviteUserToTeamReqRoleMember
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListTasksOK struct {
	Tasks      []Task     `json:"tasks"`
	Pagination Pagination `json:"pagination"`
}

// GetTasks returns the value of Tasks.
func (s *ListTasksOK) GetTasks() []Task {
	return s.Tasks
}

// GetPagination returns the value of Pagination.
func (s *ListTasksOK) GetPagination() Pagination {
	return s.Pagination
}

// SetTasks sets the value of Tasks.
func (s *ListTasksOK) SetTasks(val []Task) {
	s.Tasks = val
}

// SetPagination sets the value of Pagination.
func (s *ListTasksOK) SetPagination(val Pagination) {
	s.Pagination = val
}

func (*ListTasksOK) listTasksRes() {}

type ListTasksStatus string

const (
	ListTasksStatusTodo       ListTasksStatus = "todo"
	ListTasksStatusInProgress ListTasksStatus = "in_progress"
	ListTasksStatusDone       ListTasksStatus = "done"
)

// AllValues returns all ListTasksStatus values.
func (ListTasksStatus) AllValues() []ListTasksStatus {
	return []ListTasksStatus{
		ListTasksStatusTodo,
		ListTasksStatusInProgress,
		ListTasksStatusDone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListTasksStatus) MarshalText() ([]byte, error) {
	switch s {
	case ListTasksStatusTodo:
		return []byte(s), nil
	case ListTasksStatusInProgress:
		return []byte(s), nil
	case ListTasksStatusDone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListTasksStatus) UnmarshalText(data []byte) error {
	switch ListTasksStatus(data) {
	case ListTasksStatusTodo:
		*s = ListTasksStatusTodo
		return nil
	case ListTasksStatusInProgress:
		*s = ListTasksStatusInProgress
		return nil
	case ListTasksStatusDone:
		*s = ListTasksStatusDone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ListTeamsOK struct {
	Teams      []Team     `json:"teams"`
	Pagination Pagination `json:"pagination"`
}

// GetTeams returns the value of Teams.
func (s *ListTeamsOK) GetTeams() []Team {
	return s.Teams
}

// GetPagination returns the value of Pagination.
func (s *ListTeamsOK) GetPagination() Pagination {
	return s.Pagination
}

// SetTeams sets the value of Teams.
func (s *ListTeamsOK) SetTeams(val []Team) {
	s.Teams = val
}

// SetPagination sets the value of Pagination.
func (s *ListTeamsOK) SetPagination(val Pagination) {
	s.Pagination = val
}

func (*ListTeamsOK) listTeamsRes() {}

type LoginUserOK struct {
	// JWT-токен для авторизации.
	Token string `json:"token"`
	User  User   `json:"user"`
}

// GetToken returns the value of Token.
func (s *LoginUserOK) GetToken() string {
	return s.Token
}

// GetUser returns the value of User.
func (s *LoginUserOK) GetUser() User {
	return s.User
}

// SetToken sets the value of Token.
func (s *LoginUserOK) SetToken(val string) {
	s.Token = val
}

// SetUser sets the value of User.
func (s *LoginUserOK) SetUser(val User) {
	s.User = val
}

func (*LoginUserOK) loginUserRes() {}

type LoginUserReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginUserReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginUserReq) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginUserReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginUserReq) SetPassword(val string) {
	s.Password = val
}

// Ресурс не найден.
// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) createTaskRes()       {}
func (*NotFoundError) getTaskHistoryRes()   {}
func (*NotFoundError) inviteUserToTeamRes() {}
func (*NotFoundError) updateTaskRes()       {}

// NewOptCreateTaskReqPriority returns new OptCreateTaskReqPriority with value set to v.
func NewOptCreateTaskReqPriority(v CreateTaskReqPriority) OptCreateTaskReqPriority {
	return OptCreateTaskReqPriority{
		Value: v,
		Set:   true,
	}
}

// OptCreateTaskReqPriority is optional CreateTaskReqPriority.
type OptCreateTaskReqPriority struct {
	Value CreateTaskReqPriority
	Set   bool
}

// IsSet returns true if OptCreateTaskReqPriority was set.
func (o OptCreateTaskReqPriority) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateTaskReqPriority) Reset() {
	var v CreateTaskReqPriority
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateTaskReqPriority) SetTo(v CreateTaskReqPriority) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateTaskReqPriority) Get() (v CreateTaskReqPriority, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateTaskReqPriority) Or(d CreateTaskReqPriority) CreateTaskReqPriority {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateTaskReqStatus returns new OptCreateTaskReqStatus with value set to v.
func NewOptCreateTaskReqStatus(v CreateTaskReqStatus) OptCreateTaskReqStatus {
	return OptCreateTaskReqStatus{
		Value: v,
		Set:   true,
	}
}

// OptCreateTaskReqStatus is optional CreateTaskReqStatus.
type OptCreateTaskReqStatus struct {
	Value CreateTaskReqStatus
	Set   bool
}

// IsSet returns true if OptCreateTaskReqStatus was set.
func (o OptCreateTaskReqStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateTaskReqStatus) Reset() {
	var v CreateTaskReqStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateTaskReqStatus) SetTo(v CreateTaskReqStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateTaskReqStatus) Get() (v CreateTaskReqStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateTaskReqStatus) Or(d CreateTaskReqStatus) CreateTaskReqStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInviteUserToTeamReqRole returns new OptInviteUserToTeamReqRole with value set to v.
func NewOptInviteUserToTeamReqRole(v InviteUserToTeamReqRole) OptInviteUserToTeamReqRole {
	return OptInviteUserToTeamReqRole{
		Value: v,
		Set:   true,
	}
}

// OptInviteUserToTeamReqRole is optional InviteUserToTeamReqRole.
type OptInviteUserToTeamReqRole struct {
	Value InviteUserToTeamReqRole
	Set   bool
}

// IsSet returns true if OptInviteUserToTeamReqRole was set.
func (o OptInviteUserToTeamReqRole) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInviteUserToTeamReqRole) Reset() {
	var v InviteUserToTeamReqRole
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInviteUserToTeamReqRole) SetTo(v InviteUserToTeamReqRole) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInviteUserToTeamReqRole) Get() (v InviteUserToTeamReqRole, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInviteUserToTeamReqRole) Or(d InviteUserToTeamReqRole) InviteUserToTeamReqRole {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListTasksStatus returns new OptListTasksStatus with value set to v.
func NewOptListTasksStatus(v ListTasksStatus) OptListTasksStatus {
	return OptListTasksStatus{
		Value: v,
		Set:   true,
	}
}

// OptListTasksStatus is optional ListTasksStatus.
type OptListTasksStatus struct {
	Value ListTasksStatus
	Set   bool
}

// IsSet returns true if OptListTasksStatus was set.
func (o OptListTasksStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListTasksStatus) Reset() {
	var v ListTasksStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListTasksStatus) SetTo(v ListTasksStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListTasksStatus) Get() (v ListTasksStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListTasksStatus) Or(d ListTasksStatus) ListTasksStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt64 returns new OptNilInt64 with value set to v.
func NewOptNilInt64(v int64) OptNilInt64 {
	return OptNilInt64{
		Value: v,
		Set:   true,
	}
}

// OptNilInt64 is optional nullable int64.
type OptNilInt64 struct {
	Value int64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt64 was set.
func (o OptNilInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt64) SetTo(v int64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt64) SetToNull() {
	o.Set = true
	o.Null = true
	var v int64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateTaskReqPriority returns new OptUpdateTaskReqPriority with value set to v.
func NewOptUpdateTaskReqPriority(v UpdateTaskReqPriority) OptUpdateTaskReqPriority {
	return OptUpdateTaskReqPriority{
		Value: v,
		Set:   true,
	}
}

// OptUpdateTaskReqPriority is optional UpdateTaskReqPriority.
type OptUpdateTaskReqPriority struct {
	Value UpdateTaskReqPriority
	Set   bool
}

// IsSet returns true if OptUpdateTaskReqPriority was set.
func (o OptUpdateTaskReqPriority) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateTaskReqPriority) Reset() {
	var v UpdateTaskReqPriority
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateTaskReqPriority) SetTo(v UpdateTaskReqPriority) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateTaskReqPriority) Get() (v UpdateTaskReqPriority, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateTaskReqPriority) Or(d UpdateTaskReqPriority) UpdateTaskReqPriority {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateTaskReqStatus returns new OptUpdateTaskReqStatus with value set to v.
func NewOptUpdateTaskReqStatus(v UpdateTaskReqStatus) OptUpdateTaskReqStatus {
	return OptUpdateTaskReqStatus{
		Value: v,
		Set:   true,
	}
}

// OptUpdateTaskReqStatus is optional UpdateTaskReqStatus.
type OptUpdateTaskReqStatus struct {
	Value UpdateTaskReqStatus
	Set   bool
}

// IsSet returns true if OptUpdateTaskReqStatus was set.
func (o OptUpdateTaskReqStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateTaskReqStatus) Reset() {
	var v UpdateTaskReqStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateTaskReqStatus) SetTo(v UpdateTaskReqStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateTaskReqStatus) Get() (v UpdateTaskReqStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateTaskReqStatus) Or(d UpdateTaskReqStatus) UpdateTaskReqStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Метаданные пагинации.
// Ref: #/components/schemas/pagination
type Pagination struct {
	// Текущая страница.
	Page int32 `json:"page"`
	// Количество элементов на странице.
	PerPage int32 `json:"per_page"`
	// Всего элементов.
	Total int64 `json:"total"`
	// Всего страниц.
	TotalPages int32 `json:"total_pages"`
}

// GetPage returns the value of Page.
func (s *Pagination) GetPage() int32 {
	return s.Page
}

// GetPerPage returns the value of PerPage.
func (s *Pagination) GetPerPage() int32 {
	return s.PerPage
}

// GetTotal returns the value of Total.
func (s *Pagination) GetTotal() int64 {
	return s.Total
}

// GetTotalPages returns the value of TotalPages.
func (s *Pagination) GetTotalPages() int32 {
	return s.TotalPages
}

// SetPage sets the value of Page.
func (s *Pagination) SetPage(val int32) {
	s.Page = val
}

// SetPerPage sets the value of PerPage.
func (s *Pagination) SetPerPage(val int32) {
	s.PerPage = val
}

// SetTotal sets the value of Total.
func (s *Pagination) SetTotal(val int64) {
	s.Total = val
}

// SetTotalPages sets the value of TotalPages.
func (s *Pagination) SetTotalPages(val int32) {
	s.TotalPages = val
}

type RegisterUserOK struct {
	// JWT-токен для авторизации.
	Token string `json:"token"`
	User  User   `json:"user"`
}

// GetToken returns the value of Token.
func (s *RegisterUserOK) GetToken() string {
	return s.Token
}

// GetUser returns the value of User.
func (s *RegisterUserOK) GetUser() User {
	return s.User
}

// SetToken sets the value of Token.
func (s *RegisterUserOK) SetToken(val string) {
	s.Token = val
}

// SetUser sets the value of User.
func (s *RegisterUserOK) SetUser(val User) {
	s.User = val
}

func (*RegisterUserOK) registerUserRes() {}

type RegisterUserReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *RegisterUserReq) GetUsername() string {
	return s.Username
}

// GetEmail returns the value of Email.
func (s *RegisterUserReq) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *RegisterUserReq) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *RegisterUserReq) SetUsername(val string) {
	s.Username = val
}

// SetEmail sets the value of Email.
func (s *RegisterUserReq) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *RegisterUserReq) SetPassword(val string) {
	s.Password = val
}

// Задача.
// Ref: #/components/schemas/task
type Task struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description OptNilString   `json:"description"`
	Status      TaskStatus     `json:"status"`
	Priority    TaskPriority   `json:"priority"`
	TeamID      int64          `json:"team_id"`
	AssigneeID  OptNilInt64    `json:"assignee_id"`
	CreatedBy   int64          `json:"created_by"`
	DueDate     OptNilDateTime `json:"due_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Task) GetID() int64 {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Task) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Task) GetDescription() OptNilString {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *Task) GetStatus() TaskStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *Task) GetPriority() TaskPriority {
	return s.Priority
}

// GetTeamID returns the value of TeamID.
func (s *Task) GetTeamID() int64 {
	return s.TeamID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *Task) GetAssigneeID() OptNilInt64 {
	return s.AssigneeID
}

// GetCreatedBy returns the value of CreatedBy.
func (s *Task) GetCreatedBy() int64 {
	return s.CreatedBy
}

// GetDueDate returns the value of DueDate.
func (s *Task) GetDueDate() OptNilDateTime {
	return s.DueDate
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Task) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Task) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Task) SetID(val int64) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Task) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Task) SetDescription(val OptNilString) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *Task) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *Task) SetPriority(val TaskPriority) {
	s.Priority = val
}

// SetTeamID sets the value of TeamID.
func (s *Task) SetTeamID(val int64) {
	s.TeamID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *Task) SetAssigneeID(val OptNilInt64) {
	s.AssigneeID = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *Task) SetCreatedBy(val int64) {
	s.CreatedBy = val
}

// SetDueDate sets the value of DueDate.
func (s *Task) SetDueDate(val OptNilDateTime) {
	s.DueDate = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Task) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Task) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Task) createTaskRes() {}
func (*Task) updateTaskRes() {}

// Запись об изменении задачи (аудит).
// Ref: #/components/schemas/task_history_entry
type TaskHistoryEntry struct {
	ID        int64 `json:"id"`
	TaskID    int64 `json:"task_id"`
	ChangedBy int64 `json:"changed_by"`
	// Название изменённого поля.
	FieldName string `json:"field_name"`
	// Предыдущее значение поля.
	OldValue OptNilString `json:"old_value"`
	// Новое значение поля.
	NewValue  OptNilString `json:"new_value"`
	ChangedAt time.Time    `json:"changed_at"`
	Changer   User         `json:"changer"`
}

// GetID returns the value of ID.
func (s *TaskHistoryEntry) GetID() int64 {
	return s.ID
}

// GetTaskID returns the value of TaskID.
func (s *TaskHistoryEntry) GetTaskID() int64 {
	return s.TaskID
}

// GetChangedBy returns the value of ChangedBy.
func (s *TaskHistoryEntry) GetChangedBy() int64 {
	return s.ChangedBy
}

// GetFieldName returns the value of FieldName.
func (s *TaskHistoryEntry) GetFieldName() string {
	return s.FieldName
}

// GetOldValue returns the value of OldValue.
func (s *TaskHistoryEntry) GetOldValue() OptNilString {
	return s.OldValue
}

// GetNewValue returns the value of NewValue.
func (s *TaskHistoryEntry) GetNewValue() OptNilString {
	return s.NewValue
}

// GetChangedAt returns the value of ChangedAt.
func (s *TaskHistoryEntry) GetChangedAt() time.Time {
	return s.ChangedAt
}

// GetChanger returns the value of Changer.
func (s *TaskHistoryEntry) GetChanger() User {
	return s.Changer
}

// SetID sets the value of ID.
func (s *TaskHistoryEntry) SetID(val int64) {
	s.ID = val
}

// SetTaskID sets the value of TaskID.
func (s *TaskHistoryEntry) SetTaskID(val int64) {
	s.TaskID = val
}

// SetChangedBy sets the value of ChangedBy.
func (s *TaskHistoryEntry) SetChangedBy(val int64) {
	s.ChangedBy = val
}

// SetFieldName sets the value of FieldName.
func (s *TaskHistoryEntry) SetFieldName(val string) {
	s.FieldName = val
}

// SetOldValue sets the value of OldValue.
func (s *TaskHistoryEntry) SetOldValue(val OptNilString) {
	s.OldValue = val
}

// SetNewValue sets the value of NewValue.
func (s *TaskHistoryEntry) SetNewValue(val OptNilString) {
	s.NewValue = val
}

// SetChangedAt sets the value of ChangedAt.
func (s *TaskHistoryEntry) SetChangedAt(val time.Time) {
	s.ChangedAt = val
}

// SetChanger sets the value of Changer.
func (s *TaskHistoryEntry) SetChanger(val User) {
	s.Changer = val
}

type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
)

// AllValues returns all TaskPriority values.
func (TaskPriority) AllValues() []TaskPriority {
	return []TaskPriority{
		TaskPriorityLow,
		TaskPriorityMedium,
		TaskPriorityHigh,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskPriority) MarshalText() ([]byte, error) {
	switch s {
	case TaskPriorityLow:
		return []byte(s), nil
	case TaskPriorityMedium:
		return []byte(s), nil
	case TaskPriorityHigh:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TaskPriority) UnmarshalText(data []byte) error {
	switch TaskPriority(data) {
	case TaskPriorityLow:
		*s = TaskPriorityLow
		return nil
	case TaskPriorityMedium:
		*s = TaskPriorityMedium
		return nil
	case TaskPriorityHigh:
		*s = TaskPriorityHigh
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
)

// AllValues returns all TaskStatus values.
func (TaskStatus) AllValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusTodo,
		TaskStatusInProgress,
		TaskStatusDone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskStatus) MarshalText() ([]byte, error) {
	switch s {
	case TaskStatusTodo:
		return []byte(s), nil
	case TaskStatusInProgress:
		return []byte(s), nil
	case TaskStatusDone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TaskStatus) UnmarshalText(data []byte) error {
	switch TaskStatus(data) {
	case TaskStatusTodo:
		*s = TaskStatusTodo
		return nil
	case TaskStatusInProgress:
		*s = TaskStatusInProgress
		return nil
	case TaskStatusDone:
		*s = TaskStatusDone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Команда.
// Ref: #/components/schemas/team
type Team struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description OptNilString `json:"description"`
	CreatedBy   int64        `json:"created_by"`
	CreatedAt   time.Time    `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Team) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Team) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Team) GetDescription() OptNilString {
	return s.Description
}

// GetCreatedBy returns the value of CreatedBy.
func (s *Team) GetCreatedBy() int64 {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Team) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Team) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Team) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Team) SetDescription(val OptNilString) {
	s.Description = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *Team) SetCreatedBy(val int64) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Team) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Team) createTeamRes() {}

// Участник команды с ролью.
// Ref: #/components/schemas/team_member
type TeamMember struct {
	UserID   int64          `json:"user_id"`
	TeamID   int64          `json:"team_id"`
	Role     TeamMemberRole `json:"role"`
	JoinedAt time.Time      `json:"joined_at"`
	User     User           `json:"user"`
}

// GetUserID returns the value of UserID.
func (s *TeamMember) GetUserID() int64 {
	return s.UserID
}

// GetTeamID returns the value of TeamID.
func (s *TeamMember) GetTeamID() int64 {
	return s.TeamID
}

// GetRole returns the value of Role.
func (s *TeamMember) GetRole() TeamMemberRole {
	return s.Role
}

// GetJoinedAt returns the value of JoinedAt.
func (s *TeamMember) GetJoinedAt() time.Time {
	return s.JoinedAt
}

// GetUser returns the value of User.
func (s *TeamMember) GetUser() User {
	return s.User
}

// SetUserID sets the value of UserID.
func (s *TeamMember) SetUserID(val int64) {
	s.UserID = val
}

// SetTeamID sets the value of TeamID.
func (s *TeamMember) SetTeamID(val int64) {
	s.TeamID = val
}

// SetRole sets the value of Role.
func (s *TeamMember) SetRole(val TeamMemberRole) {
	s.Role = val
}

// SetJoinedAt sets the value of JoinedAt.
func (s *TeamMember) SetJoinedAt(val time.Time) {
	s.JoinedAt = val
}

// SetUser sets the value of User.
func (s *TeamMember) SetUser(val User) {
	s.User = val
}

func (*TeamMember) inviteUserToTeamRes() {}

type TeamMemberRole string

const (
	TeamMemberRoleOwner  TeamMemberRole = "owner"
	TeamMemberRoleAdmin  TeamMemberRole = "admin"
	TeamMemberRoleMember TeamMemberRole = "member"
)

// AllValues returns all TeamMemberRole values.
func (TeamMemberRole) AllValues() []TeamMemberRole {
	return []TeamMemberRole{
		TeamMemberRoleOwner,
		TeamMemberRoleAdmin,
		TeamMemberRoleMember,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TeamMemberRole) MarshalText() ([]byte, error) {
	switch s {
	case TeamMemberRoleOwner:
		return []byte(s), nil
	case TeamMemberRoleAdmin:
		return []byte(s), nil
	case TeamMemberRoleMember:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TeamMemberRole) UnmarshalText(data []byte) error {
	switch TeamMemberRole(data) {
	case TeamMemberRoleOwner:
		*s = TeamMemberRoleOwner
		return nil
	case TeamMemberRoleAdmin:
		*s = TeamMemberRoleAdmin
		return nil
	case TeamMemberRoleMember:
		*s = TeamMemberRoleMember
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ошибка аутентификации.
// Ref: #/components/schemas/unauthorized_error
type UnauthorizedError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() int32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val int32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val string) {
	s.Message = val
}

func (*UnauthorizedError) createTaskRes()       {}
func (*UnauthorizedError) createTeamRes()       {}
func (*UnauthorizedError) getTaskHistoryRes()   {}
func (*UnauthorizedError) inviteUserToTeamRes() {}
func (*UnauthorizedError) listTasksRes()        {}
func (*UnauthorizedError) listTeamsRes()        {}
func (*UnauthorizedError) loginUserRes()        {}
func (*UnauthorizedError) updateTaskRes()       {}

type UpdateTaskReq struct {
	Title       OptString                `json:"title"`
	Description OptString                `json:"description"`
	Status      OptUpdateTaskReqStatus   `json:"status"`
	Priority    OptUpdateTaskReqPriority `json:"priority"`
	AssigneeID  OptNilInt64              `json:"assignee_id"`
	DueDate     OptNilDateTime           `json:"due_date"`
}

// GetTitle returns the value of Title.
func (s *UpdateTaskReq) GetTitle() OptString {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *UpdateTaskReq) GetDescription() OptString {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *UpdateTaskReq) GetStatus() OptUpdateTaskReqStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *UpdateTaskReq) GetPriority() OptUpdateTaskReqPriority {
	return s.Priority
}

// GetAssigneeID returns the value of AssigneeID.
func (s *UpdateTaskReq) GetAssigneeID() OptNilInt64 {
	return s.AssigneeID
}

// GetDueDate returns the value of DueDate.
func (s *UpdateTaskReq) GetDueDate() OptNilDateTime {
	return s.DueDate
}

// SetTitle sets the value of Title.
func (s *UpdateTaskReq) SetTitle(val OptString) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *UpdateTaskReq) SetDescription(val OptString) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *UpdateTaskReq) SetStatus(val OptUpdateTaskReqStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *UpdateTaskReq) SetPriority(val OptUpdateTaskReqPriority) {
	s.Priority = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *UpdateTaskReq) SetAssigneeID(val OptNilInt64) {
	s.AssigneeID = val
}

// SetDueDate sets the value of DueDate.
func (s *UpdateTaskReq) SetDueDate(val OptNilDateTime) {
	s.DueDate = val
}

type UpdateTaskReqPriority string

const (
	UpdateTaskReqPriorityLow    UpdateTaskReqPriority = "low"
	UpdateTaskReqPriorityMedium UpdateTaskReqPriority = "medium"
	UpdateTaskReqPriorityHigh   UpdateTaskReqPriority = "high"
)

// AllValues returns all UpdateTaskReqPriority values.
func (UpdateTaskReqPriority) AllValues() []UpdateTaskReqPriority {
	return []UpdateTaskReqPriority{
		UpdateTaskReqPriorityLow,
		UpdateTaskReqPriorityMedium,
		UpdateTaskReqPriorityHigh,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateTaskReqPriority) MarshalText() ([]byte, error) {
	switch s {
	case UpdateTaskReqPriorityLow:
		return []byte(s), nil
	case UpdateTaskReqPriorityMedium:
		return []byte(s), nil
	case UpdateTaskReqPriorityHigh:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateTaskReqPriority) UnmarshalText(data []byte) error {
	switch UpdateTaskReqPriority(data) {
	case UpdateTaskReqPriorityLow:
		*s = UpdateTaskReqPriorityLow
		return nil
	case UpdateTaskReqPriorityMedium:
		*s = UpdateTaskReqPriorityMedium
		return nil
	case UpdateTaskReqPriorityHigh:
		*s = UpdateTaskReqPriorityHigh
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpdateTaskReqStatus string

const (
	UpdateTaskReqStatusTodo       UpdateTaskReqStatus = "todo"
	UpdateTaskReqStatusInProgress UpdateTaskReqStatus = "in_progress"
	UpdateTaskReqStatusDone       UpdateTaskReqStatus = "done"
)

// AllValues returns all UpdateTaskReqStatus values.
func (UpdateTaskReqStatus) AllValues() []UpdateTaskReqStatus {
	return []UpdateTaskReqStatus{
		UpdateTaskReqStatusTodo,
		UpdateTaskReqStatusInProgress,
		UpdateTaskReqStatusDone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateTaskReqStatus) MarshalText() ([]byte, error) {
	switch s {
	case UpdateTaskReqStatusTodo:
		return []byte(s), nil
	case UpdateTaskReqStatusInProgress:
		return []byte(s), nil
	case UpdateTaskReqStatusDone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateTaskReqStatus) UnmarshalText(data []byte) error {
	switch UpdateTaskReqStatus(data) {
	case UpdateTaskReqStatusTodo:
		*s = UpdateTaskReqStatusTodo
		return nil
	case UpdateTaskReqStatusInProgress:
		*s = UpdateTaskReqStatusInProgress
		return nil
	case UpdateTaskReqStatusDone:
		*s = UpdateTaskReqStatusDone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Пользователь системы.
// Ref: #/components/schemas/user
type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *User) GetID() int64 {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val int64) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}
