// Code generated by ogen, DO NOT EDIT.

package tasks_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTaskOperation       OperationName = "CreateTask"
	CreateTeamOperation       OperationName = "CreateTeam"
	GetTaskHistoryOperation   OperationName = "GetTaskHistory"
	InviteUserToTeamOperation OperationName = "InviteUserToTeam"
	ListTasksOperation        OperationName = "ListTasks"
	ListTeamsOperation        OperationName = "ListTeams"
	LoginUserOperation        OperationName = "LoginUser"
	RegisterUserOperation     OperationName = "RegisterUser"
	UpdateTaskOperation       OperationName = "UpdateTask"
)
