// Code generated by ogen, DO NOT EDIT.

package tasks_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateTask implements CreateTask operation.
	//
	// Создать новую задачу (только для членов команды).
	//
	// POST /api/v1/tasks
	CreateTask(ctx context.Context, req *CreateTaskReq) (CreateTaskRes, error)
	// CreateTeam implements CreateTeam operation.
	//
	// Создать новую команду (текущий пользователь
	// становится owner).
	//
	// POST /api/v1/teams
	CreateTeam(ctx context.Context, req *CreateTeamReq) (CreateTeamRes, error)
	// GetTaskHistory implements GetTaskHistory operation.
	//
	// История изменений задачи.
	//
	// GET /api/v1/tasks/{id}/history
	GetTaskHistory(ctx context.Context, params GetTaskHistoryParams) (GetTaskHistoryRes, error)
	// InviteUserToTeam implements InviteUserToTeam operation.
	//
	// Пригласить пользователя в команду (только owner/admin).
	//
	// POST /api/v1/teams/{id}/invite
	InviteUserToTeam(ctx context.Context, req *InviteUserToTeamReq, params InviteUserToTeamParams) (InviteUserToTeamRes, error)
	// ListTasks implements ListTasks operation.
	//
	// Список задач с фильтрацией и пагинацией.
	//
	// GET /api/v1/tasks
	ListTasks(ctx context.Context, params ListTasksParams) (ListTasksRes, error)
	// ListTeams implements ListTeams operation.
	//
	// Список команд, в которых состоит текущий пользователь.
	//
	// GET /api/v1/teams
	ListTeams(ctx context.Context, params ListTeamsParams) (ListTeamsRes, error)
	// LoginUser implements LoginUser operation.
	//
	// Аутентификация пользователя и получение JWT-токена.
	//
	// POST /api/v1/login
	LoginUser(ctx context.Context, req *LoginUserReq) (LoginUserRes, error)
	// RegisterUser implements RegisterUser operation.
	//
	// Регистрация нового пользователя в системе.
	//
	// POST /api/v1/register
	RegisterUser(ctx context.Context, req *RegisterUserReq) (RegisterUserRes, error)
	// UpdateTask implements UpdateTask operation.
	//
	// Обновить задачу (проверка прав доступа).
	//
	// PUT /api/v1/tasks/{id}
	UpdateTask(ctx context.Context, req *UpdateTaskReq, params UpdateTaskParams) (UpdateTaskRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
