// Code generated by ogen, DO NOT EDIT.
package tasks_v1

type CreateTaskRes interface {
	createTaskRes()
}

type CreateTeamRes interface {
	createTeamRes()
}

type GetTaskHistoryRes interface {
	getTaskHistoryRes()
}

type InviteUserToTeamRes interface {
	inviteUserToTeamRes()
}

type ListTasksRes interface {
	listTasksRes()
}

type ListTeamsRes interface {
	listTeamsRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type RegisterUserRes interface {
	registerUserRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}
