// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	user "github.com/delyke/tasks_and_commands_service/internal/domain/user"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

type TokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGenerator) EXPECT() *TokenGenerator_Expecter {
	return &TokenGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: userID, email, ttl, issuer
func (_m *TokenGenerator) Generate(userID user.ID, email string, ttl time.Duration, issuer string) (string, error) {
	ret := _m.Called(userID, email, ttl, issuer)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(user.ID, string, time.Duration, string) (string, error)); ok {
		return rf(userID, email, ttl, issuer)
	}
	if rf, ok := ret.Get(0).(func(user.ID, string, time.Duration, string) string); ok {
		r0 = rf(userID, email, ttl, issuer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(user.ID, string, time.Duration, string) error); ok {
		r1 = rf(userID, email, ttl, issuer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type TokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID user.ID
//   - email string
//   - ttl time.Duration
//   - issuer string
func (_e *TokenGenerator_Expecter) Generate(userID interface{}, email interface{}, ttl interface{}, issuer interface{}) *TokenGenerator_Generate_Call {
	return &TokenGenerator_Generate_Call{Call: _e.mock.On("Generate", userID, email, ttl, issuer)}
}

func (_c *TokenGenerator_Generate_Call) Run(run func(userID user.ID, email string, ttl time.Duration, issuer string)) *TokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(user.ID), args[1].(string), args[2].(time.Duration), args[3].(string))
	})
	return _c
}

func (_c *TokenGenerator_Generate_Call) Return(_a0 string, _a1 error) *TokenGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenGenerator_Generate_Call) RunAndReturn(run func(user.ID, string, time.Duration, string) (string, error)) *TokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
