// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

type Config_Expecter struct {
	mock *mock.Mock
}

func (_m *Config) EXPECT() *Config_Expecter {
	return &Config_Expecter{mock: &_m.Mock}
}

// AccessTokenTTL provides a mock function with no fields
func (_m *Config) AccessTokenTTL() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessTokenTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// Config_AccessTokenTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessTokenTTL'
type Config_AccessTokenTTL_Call struct {
	*mock.Call
}

// AccessTokenTTL is a helper method to define mock.On call
func (_e *Config_Expecter) AccessTokenTTL() *Config_AccessTokenTTL_Call {
	return &Config_AccessTokenTTL_Call{Call: _e.mock.On("AccessTokenTTL")}
}

func (_c *Config_AccessTokenTTL_Call) Run(run func()) *Config_AccessTokenTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Config_AccessTokenTTL_Call) Return(_a0 time.Duration) *Config_AccessTokenTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Config_AccessTokenTTL_Call) RunAndReturn(run func() time.Duration) *Config_AccessTokenTTL_Call {
	_c.Call.Return(run)
	return _c
}

// Issuer provides a mock function with no fields
func (_m *Config) Issuer() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Issuer")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Config_Issuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issuer'
type Config_Issuer_Call struct {
	*mock.Call
}

// Issuer is a helper method to define mock.On call
func (_e *Config_Expecter) Issuer() *Config_Issuer_Call {
	return &Config_Issuer_Call{Call: _e.mock.On("Issuer")}
}

func (_c *Config_Issuer_Call) Run(run func()) *Config_Issuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Config_Issuer_Call) Return(_a0 string) *Config_Issuer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Config_Issuer_Call) RunAndReturn(run func() string) *Config_Issuer_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfig creates a new instance of Config. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *Config {
	mock := &Config{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
