// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	task "github.com/delyke/tasks_and_commands_service/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// AnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type AnalyticsRepository struct {
	mock.Mock
}

type AnalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalyticsRepository) EXPECT() *AnalyticsRepository_Expecter {
	return &AnalyticsRepository_Expecter{mock: &_m.Mock}
}

// FindOrphanedAssignees provides a mock function with given fields: ctx
func (_m *AnalyticsRepository) FindOrphanedAssignees(ctx context.Context) ([]*task.OrphanedTask, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindOrphanedAssignees")
	}

	var r0 []*task.OrphanedTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*task.OrphanedTask, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*task.OrphanedTask); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.OrphanedTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsRepository_FindOrphanedAssignees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrphanedAssignees'
type AnalyticsRepository_FindOrphanedAssignees_Call struct {
	*mock.Call
}

// FindOrphanedAssignees is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AnalyticsRepository_Expecter) FindOrphanedAssignees(ctx interface{}) *AnalyticsRepository_FindOrphanedAssignees_Call {
	return &AnalyticsRepository_FindOrphanedAssignees_Call{Call: _e.mock.On("FindOrphanedAssignees", ctx)}
}

func (_c *AnalyticsRepository_FindOrphanedAssignees_Call) Run(run func(ctx context.Context)) *AnalyticsRepository_FindOrphanedAssignees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AnalyticsRepository_FindOrphanedAssignees_Call) Return(_a0 []*task.OrphanedTask, _a1 error) *AnalyticsRepository_FindOrphanedAssignees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsRepository_FindOrphanedAssignees_Call) RunAndReturn(run func(context.Context) ([]*task.OrphanedTask, error)) *AnalyticsRepository_FindOrphanedAssignees_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamStats provides a mock function with given fields: ctx
func (_m *AnalyticsRepository) GetTeamStats(ctx context.Context) ([]*task.TeamStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamStats")
	}

	var r0 []*task.TeamStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*task.TeamStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*task.TeamStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.TeamStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsRepository_GetTeamStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamStats'
type AnalyticsRepository_GetTeamStats_Call struct {
	*mock.Call
}

// GetTeamStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AnalyticsRepository_Expecter) GetTeamStats(ctx interface{}) *AnalyticsRepository_GetTeamStats_Call {
	return &AnalyticsRepository_GetTeamStats_Call{Call: _e.mock.On("GetTeamStats", ctx)}
}

func (_c *AnalyticsRepository_GetTeamStats_Call) Run(run func(ctx context.Context)) *AnalyticsRepository_GetTeamStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AnalyticsRepository_GetTeamStats_Call) Return(_a0 []*task.TeamStats, _a1 error) *AnalyticsRepository_GetTeamStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsRepository_GetTeamStats_Call) RunAndReturn(run func(context.Context) ([]*task.TeamStats, error)) *AnalyticsRepository_GetTeamStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopCreatorsByTeam provides a mock function with given fields: ctx, limit
func (_m *AnalyticsRepository) GetTopCreatorsByTeam(ctx context.Context, limit int) ([]*task.TopCreator, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopCreatorsByTeam")
	}

	var r0 []*task.TopCreator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*task.TopCreator, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*task.TopCreator); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.TopCreator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsRepository_GetTopCreatorsByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopCreatorsByTeam'
type AnalyticsRepository_GetTopCreatorsByTeam_Call struct {
	*mock.Call
}

// GetTopCreatorsByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *AnalyticsRepository_Expecter) GetTopCreatorsByTeam(ctx interface{}, limit interface{}) *AnalyticsRepository_GetTopCreatorsByTeam_Call {
	return &AnalyticsRepository_GetTopCreatorsByTeam_Call{Call: _e.mock.On("GetTopCreatorsByTeam", ctx, limit)}
}

func (_c *AnalyticsRepository_GetTopCreatorsByTeam_Call) Run(run func(ctx context.Context, limit int)) *AnalyticsRepository_GetTopCreatorsByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *AnalyticsRepository_GetTopCreatorsByTeam_Call) Return(_a0 []*task.TopCreator, _a1 error) *AnalyticsRepository_GetTopCreatorsByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsRepository_GetTopCreatorsByTeam_Call) RunAndReturn(run func(context.Context, int) ([]*task.TopCreator, error)) *AnalyticsRepository_GetTopCreatorsByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalyticsRepository creates a new instance of AnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepository {
	mock := &AnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
