// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	task "github.com/delyke/tasks_and_commands_service/internal/domain/task"
	mock "github.com/stretchr/testify/mock"

	team "github.com/delyke/tasks_and_commands_service/internal/domain/team"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Repository) Create(ctx context.Context, _a1 *task.Task) (task.ID, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 task.ID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) (task.ID, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) task.ID); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(task.ID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *task.Task) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *task.Task
func (_e *Repository_Expecter) Create(ctx interface{}, _a1 interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, _a1 *task.Task)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Task))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 task.ID, _a1 error) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, *task.Task) (task.ID, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id task.ID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id task.ID
func (_e *Repository_Expecter) Delete(ctx interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, id task.ID)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.ID))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, task.ID) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id task.ID) (*task.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) (*task.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) *task.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Repository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id task.ID
func (_e *Repository_Expecter) GetByID(ctx interface{}, id interface{}) *Repository_GetByID_Call {
	return &Repository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Repository_GetByID_Call) Run(run func(ctx context.Context, id task.ID)) *Repository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.ID))
	})
	return _c
}

func (_c *Repository_GetByID_Call) Return(_a0 *task.Task, _a1 error) *Repository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetByID_Call) RunAndReturn(run func(context.Context, task.ID) (*task.Task, error)) *Repository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *Repository) List(ctx context.Context, filter *task.Filter) ([]*task.Task, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*task.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Filter) ([]*task.Task, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *task.Filter) []*task.Task); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *task.Filter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *task.Filter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *task.Filter
func (_e *Repository_Expecter) List(ctx interface{}, filter interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, filter *task.Filter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Filter))
	})
	return _c
}

func (_c *Repository_List_Call) Return(_a0 []*task.Task, _a1 int64, _a2 error) *Repository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, *task.Filter) ([]*task.Task, int64, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTeam provides a mock function with given fields: ctx, teamID, limit, offset
func (_m *Repository) ListByTeam(ctx context.Context, teamID team.ID, limit int, offset int) ([]*task.Task, int64, error) {
	ret := _m.Called(ctx, teamID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByTeam")
	}

	var r0 []*task.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, int, int) ([]*task.Task, int64, error)); ok {
		return rf(ctx, teamID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, team.ID, int, int) []*task.Task); ok {
		r0 = rf(ctx, teamID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, team.ID, int, int) int64); ok {
		r1 = rf(ctx, teamID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, team.ID, int, int) error); ok {
		r2 = rf(ctx, teamID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_ListByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTeam'
type Repository_ListByTeam_Call struct {
	*mock.Call
}

// ListByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID team.ID
//   - limit int
//   - offset int
func (_e *Repository_Expecter) ListByTeam(ctx interface{}, teamID interface{}, limit interface{}, offset interface{}) *Repository_ListByTeam_Call {
	return &Repository_ListByTeam_Call{Call: _e.mock.On("ListByTeam", ctx, teamID, limit, offset)}
}

func (_c *Repository_ListByTeam_Call) Run(run func(ctx context.Context, teamID team.ID, limit int, offset int)) *Repository_ListByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(team.ID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *Repository_ListByTeam_Call) Return(_a0 []*task.Task, _a1 int64, _a2 error) *Repository_ListByTeam_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_ListByTeam_Call) RunAndReturn(run func(context.Context, team.ID, int, int) ([]*task.Task, int64, error)) *Repository_ListByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Repository) Update(ctx context.Context, _a1 *task.Task) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *task.Task
func (_e *Repository_Expecter) Update(ctx interface{}, _a1 interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, _a1 *task.Task)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Task))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *task.Task) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
