// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	task "github.com/delyke/tasks_and_commands_service/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// HistoryRepository is an autogenerated mock type for the HistoryRepository type
type HistoryRepository struct {
	mock.Mock
}

type HistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HistoryRepository) EXPECT() *HistoryRepository_Expecter {
	return &HistoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, history
func (_m *HistoryRepository) Create(ctx context.Context, history *task.History) (task.HistoryID, error) {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 task.HistoryID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.History) (task.HistoryID, error)); ok {
		return rf(ctx, history)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *task.History) task.HistoryID); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Get(0).(task.HistoryID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *task.History) error); ok {
		r1 = rf(ctx, history)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HistoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type HistoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - history *task.History
func (_e *HistoryRepository_Expecter) Create(ctx interface{}, history interface{}) *HistoryRepository_Create_Call {
	return &HistoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *HistoryRepository_Create_Call) Run(run func(ctx context.Context, history *task.History)) *HistoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.History))
	})
	return _c
}

func (_c *HistoryRepository_Create_Call) Return(_a0 task.HistoryID, _a1 error) *HistoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HistoryRepository_Create_Call) RunAndReturn(run func(context.Context, *task.History) (task.HistoryID, error)) *HistoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTask provides a mock function with given fields: ctx, taskID
func (_m *HistoryRepository) ListByTask(ctx context.Context, taskID task.ID) ([]*task.History, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []*task.History
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) ([]*task.History, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) []*task.History); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.History)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.ID) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HistoryRepository_ListByTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTask'
type HistoryRepository_ListByTask_Call struct {
	*mock.Call
}

// ListByTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID task.ID
func (_e *HistoryRepository_Expecter) ListByTask(ctx interface{}, taskID interface{}) *HistoryRepository_ListByTask_Call {
	return &HistoryRepository_ListByTask_Call{Call: _e.mock.On("ListByTask", ctx, taskID)}
}

func (_c *HistoryRepository_ListByTask_Call) Run(run func(ctx context.Context, taskID task.ID)) *HistoryRepository_ListByTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.ID))
	})
	return _c
}

func (_c *HistoryRepository_ListByTask_Call) Return(_a0 []*task.History, _a1 error) *HistoryRepository_ListByTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HistoryRepository_ListByTask_Call) RunAndReturn(run func(context.Context, task.ID) ([]*task.History, error)) *HistoryRepository_ListByTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewHistoryRepository creates a new instance of HistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistoryRepository {
	mock := &HistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
