// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	task "github.com/delyke/tasks_and_commands_service/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// CommentRepository is an autogenerated mock type for the CommentRepository type
type CommentRepository struct {
	mock.Mock
}

type CommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentRepository) EXPECT() *CommentRepository_Expecter {
	return &CommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, comment
func (_m *CommentRepository) Create(ctx context.Context, comment *task.Comment) (task.CommentID, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 task.CommentID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Comment) (task.CommentID, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *task.Comment) task.CommentID); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Get(0).(task.CommentID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *task.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *task.Comment
func (_e *CommentRepository_Expecter) Create(ctx interface{}, comment interface{}) *CommentRepository_Create_Call {
	return &CommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *CommentRepository_Create_Call) Run(run func(ctx context.Context, comment *task.Comment)) *CommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Comment))
	})
	return _c
}

func (_c *CommentRepository_Create_Call) Return(_a0 task.CommentID, _a1 error) *CommentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepository_Create_Call) RunAndReturn(run func(context.Context, *task.Comment) (task.CommentID, error)) *CommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CommentRepository) Delete(ctx context.Context, id task.CommentID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, task.CommentID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id task.CommentID
func (_e *CommentRepository_Expecter) Delete(ctx interface{}, id interface{}) *CommentRepository_Delete_Call {
	return &CommentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CommentRepository_Delete_Call) Run(run func(ctx context.Context, id task.CommentID)) *CommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.CommentID))
	})
	return _c
}

func (_c *CommentRepository_Delete_Call) Return(_a0 error) *CommentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CommentRepository_Delete_Call) RunAndReturn(run func(context.Context, task.CommentID) error) *CommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CommentRepository) GetByID(ctx context.Context, id task.CommentID) (*task.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *task.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.CommentID) (*task.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.CommentID) *task.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.CommentID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id task.CommentID
func (_e *CommentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CommentRepository_GetByID_Call {
	return &CommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CommentRepository_GetByID_Call) Run(run func(ctx context.Context, id task.CommentID)) *CommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.CommentID))
	})
	return _c
}

func (_c *CommentRepository_GetByID_Call) Return(_a0 *task.Comment, _a1 error) *CommentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepository_GetByID_Call) RunAndReturn(run func(context.Context, task.CommentID) (*task.Comment, error)) *CommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTask provides a mock function with given fields: ctx, taskID
func (_m *CommentRepository) ListByTask(ctx context.Context, taskID task.ID) ([]*task.Comment, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []*task.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) ([]*task.Comment, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.ID) []*task.Comment); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.ID) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentRepository_ListByTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTask'
type CommentRepository_ListByTask_Call struct {
	*mock.Call
}

// ListByTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID task.ID
func (_e *CommentRepository_Expecter) ListByTask(ctx interface{}, taskID interface{}) *CommentRepository_ListByTask_Call {
	return &CommentRepository_ListByTask_Call{Call: _e.mock.On("ListByTask", ctx, taskID)}
}

func (_c *CommentRepository_ListByTask_Call) Run(run func(ctx context.Context, taskID task.ID)) *CommentRepository_ListByTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.ID))
	})
	return _c
}

func (_c *CommentRepository_ListByTask_Call) Return(_a0 []*task.Comment, _a1 error) *CommentRepository_ListByTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentRepository_ListByTask_Call) RunAndReturn(run func(context.Context, task.ID) ([]*task.Comment, error)) *CommentRepository_ListByTask_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, comment
func (_m *CommentRepository) Update(ctx context.Context, comment *task.Comment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Comment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *task.Comment
func (_e *CommentRepository_Expecter) Update(ctx interface{}, comment interface{}) *CommentRepository_Update_Call {
	return &CommentRepository_Update_Call{Call: _e.mock.On("Update", ctx, comment)}
}

func (_c *CommentRepository_Update_Call) Run(run func(ctx context.Context, comment *task.Comment)) *CommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Comment))
	})
	return _c
}

func (_c *CommentRepository_Update_Call) Return(_a0 error) *CommentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CommentRepository_Update_Call) RunAndReturn(run func(context.Context, *task.Comment) error) *CommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommentRepository creates a new instance of CommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepository {
	mock := &CommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
